name: Github Release

on:
  release:
    types: [published]

env:
  ARTIFACT_NAME: release

jobs:
  build:
    uses: ./.github/workflows/flutter_build.yml
    secrets: inherit
    with:
      artifactName: ${{ env.ARTIFACT_NAME }}

  add-artifacts-to-release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}

    - name: Add artifacts to release
      uses: softprops/action-gh-release@v1
      with:
        files: 'release/*.apk'
